### PR TITLE
Fix lead recovery in page hit handling

### LINKED ISSUE #97: Fatal error in PageModel
Saw this in the "mautic_prod…" logs:

> [2018-01-25 00:01:00] mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Mautic\LeadBundle\Model\LeadModel::setCurrentLead() must be an instance of Mautic\LeadBundle\Entity\Lead, null given, called in /var/www/html/app/bundles/PageBundle/Model/PageModel.php on line 472 and defined (uncaught exception) at /var/www/html/app/bundles/LeadBundle/Model/LeadModel.php line 952 while running console command `mauldin:page:hits` [] []

https://github.com/MauldinEconomics/mautic/blob/341f91d5b43cc39ff0dfc9166a1f8632e640b64f/app/bundles/PageBundle/Model/PageModel.php#L472

This may fix the click tracking issue.

### PR DESCRIPTION
**Pull request by filipelbc**
Fixes #97

### CODE REVIEW

File: app/bundles/PageBundle/Model/PageModel.php [hunk 1]
```diff
@@ -469,6 +469,9 @@ public function consumeHitPage($pageId, $pageType, Request $request, $code = '20
         $lead = null;
         if(null !== $leadId) {
```
Comment (maxlawton) [inline app/bundles/PageBundle/Model/PageModel.php]: Violates PSR-2: 

### [5.1. if, elseif, else](http://www.php-fig.org/psr/psr-2/#51-if-elseif-else)

> An `if` structure looks like the following. Note the placement of parentheses, **spaces**, and braces; and that `else` and `elseif` are on the same line as the closing brace from the earlier body.
>
> ```php
> <?php
> if ($expr1) {
>     // if body
> } elseif ($expr2) {
>     // elseif body
> } else {
>     // else body;
> }
> ```

Probably not worth fixing in this PR since the whole page/hit tracking is a core conflict, but worth noting in the interest of forming habits that will help us with upstream approval.

File: app/bundles/PageBundle/Model/PageModel.php [hunk 2]
```diff
@@ -469,6 +469,9 @@ public function consumeHitPage($pageId, $pageType, Request $request, $code = '20
...
             $lead = $this->leadModel->getEntity($leadId);
+            if($lead === null){
+                $lead = $this->leadModel->getContactFromRequest($query === null ?  [] : $query,$request);
```
Comment (maxlawton) [inline app/bundles/PageBundle/Model/PageModel.php]: Another PSR-2 violation:

### [4.6. Method and Function Calls](http://www.php-fig.org/psr/psr-2/#46-method-and-function-calls)

> In the argument list, there MUST NOT be a space before each comma, and there MUST be one space after each comma.

File: app/bundles/PageBundle/Model/PageModel.php (hunk 1 above)
Comment (filipelbc) [reply app/bundles/PageBundle/Model/PageModel.php]: Most probably we are going to discard all our changes in favor of upstream when refactoring, since upstream already has the same functionality. That is why I would not bother with style.

**Comment by filipelbc** [comment]
@jojomnky Could you merge and deploy this?
